spring.application.name=game
# Accepts 'filesystem' or 'memory'
game.repository=filesystem

# Accepts 'ExactHit' or 'CrossTheFinishLine' (same as for filesystem)
game.wincondition=ExactHit

# Accepts 'HitsDoNothing' or 'HitsForfeitTurn' (same as for filesystem)
game.hitcondition=HitsDoNothing

# Accepts 2 or 4
game.numberofpieces=4

# Accepts 1 or 2
game.numberofdice=1

# Accepts 'twowayteleporter' or 'onewayteleporter' or 'mix' or 'noteleporter'
game.teleporterstrategy=mix
