# To use me, move me to src/main/resources/application.properties

spring.application.name=game
game.repository=filesystem
game.wincondition=CrossTheFinishLine
game.hitcondition=HitsDoNothing
game.numberofpieces=2
game.numberofdice=1
game.teleporterstrategy=onewayteleporter
